[tools]
"aqua:bitnami-labs/sealed-secrets" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:helm/helm" = "latest"
"aqua:istio/istio/istioctl" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:kubernetes/kubectl" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:opentofu/opentofu" = "latest"
"aqua:stern/stern" = "latest"
"aqua:derailed/k9s" = "latest"
"github:Azure/kubelogin" = "latest"
"github:pressly/goose" = "latest"
go = "latest"
"go:github.com/spf13/cobra-cli" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/joho/godotenv/cmd/godotenv" = "latest"
"github:caarlos0/timer" = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
rust = "latest"
"cargo:topgrade" = "latest"
"go:github.com/gohugoio/hugo" = "0.155.3"
