---
- name: Install all packages listed in packages.txt
  hosts: localhost
  become: yes

  vars:
    package_list_file: "packages.txt"

  tasks:
    - name: Load package list
      set_fact:
        pkg_list: "{{ lookup('file', 'packages.txt').splitlines() }}"


    - name: Ensure all listed packages are installed
      ansible.builtin.pacman:
        name: "{{ pkg_list }}"
        state: present
