-- Workspace rules wiki https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- Add your workspace rules here. Example below
-- hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true, persistent = true })
